### ISSUE TITLE
Cannot open load file: No such file or directory, w

### ISSUE THREAD

**Issue by jcguu95** [lepisma/pile#35]
In `pile-serve.el`, a package `w` is required. I cannot find it by `M-x package-install`. Is that another package that is written by you and is not yet released to the public?

By the way, I really like the way you set up your website. Elegant, pleasant, and all organized by org files. Thank you for making this!

**Comment by lepisma** [comment]
[Yup](https://github.com/lepisma/w.el/). I mostly end up linking to github repo in my emacs config so never had to think about releasing packages (say) in melpa.

> By the way, I really like the way you set up your website. Elegant, pleasant, and all organized by org files.

Thanks!
